=== bumpybox/pype-setup/deploy/deploy_schema-1.0.json
{
  "$schema": "http://json-schema.org/schema#",

  "title": "pype:deployment-schema",
  "description": "A product in the catalog",
  "type": "object",

  "properties": {
    "PYPE_CONFIG": {
      "description": "Env variable pointing to current pype config repo",
      "type": "string"
    },
    "init_env": {
      "description": "Environment files in PYPE_CONFIG to load by default.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repositories": {
      "description": "Array of repositories used for Pype",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "url"],
        "properties": {
          "name": {
            "type": "string",
            "description": "Repository name used as directory name containing it"
          },
          "url": {
            "type": "string",
            "description": "URL used to clone repository"
          },
          "branch": {
              "type": "string",
              "description": "name of branch to checkout"
          },
          "tag": {
            "type": "string",
            "description": "name of tag to checkout"
          },
          "ref": {
            "type": "string",
            "description": "git ref to checkout"
          }
        },
        "oneOf": [
            {
              "required": ["branch"]
            },
            {
              "required": ["tag"]
            },
            {
              "required": ["ref"]
            }
        ]
      }
    },
    "pip": {
      "description": "Pip dependencies installed to environment",
      "type": "array"
    },
    "archive_files": {
      "description": "Array of zip files for vendor usage.",
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
            {"required": ["extract_path", "url", "archive_type"]},
            {"required": ["extract_path", "google_id", "archive_type"]},
            {"required": ["extract_path", "vendor", "archive_type"]}
        ],
        "properties": {
          "extract_path": {
            "type": "string",
            "description": "Archive file will be extracted into this path. Result will be concatenated: {$PYPE_SETUP_PATH}/{extract_path} - Example: vendor/bin/ffmpeg"
          },
          "url": {
            "type": "string",
            "description": "URL used to download zip file."
          },
          "md5_url": {
            "type": "string",
            "description": "URL of MD5 checksum."
          },
          "vendor": {
            "type": "string",
            "description": "path in vendor/packages"
          },
          "archive_type": {
            "type": "string",
            "description": "Type of archive file (from enum)",
            "enum": ["zip", "tar", "tgz", "tar.gz", "tar.xz", "tar.bz2"]
          },
          "skip_first_subfolder": {
              "type": "boolean",
              "description": "Subfolders of main archive folder will be extracted if set to true (expected that main archive folder is only one)"
          }
        }
      }
    }
  },
  "required": ["repositories", "PYPE_CONFIG", "init_env"]
}

=== bumpybox/pype-setup/deploy/deploy.json
{
	"PYPE_CONFIG": "{PYPE_ROOT}/repos/pype-config",
  "init_env": ["global", "avalon", "ftrack", "deadline", "clockify"],
  "repositories": [{
      "name": "avalon-core",
      "url": "https://github.com/pypeclub/avalon-core.git",
      "branch": "2.7.0-pype"
    },
    {
      "name": "avalon-launcher",
      "url": "https://github.com/pypeclub/avalon-launcher.git",
      "branch": "develop"
    },
    {
      "name": "pyblish-base",
      "url": "https://github.com/pyblish/pyblish-base.git",
      "branch": "master"
    },
    {
      "name": "pyblish-lite",
      "url": "https://github.com/pypeclub/pyblish-lite.git",
      "branch": "master"
    },
    {
      "name": "maya-look-assigner",
      "url": "https://github.com/pypeclub/maya-look-assigner.git",
      "branch": "master"
    },
    {
      "name": "pype",
      "url": "https://github.com/pypeclub/pype.git",
      "tag": "2.7.0"
    },
    {
      "name": "pype-config",
      "url": "https://github.com/pypeclub/pype-config.git",
      "tag": "2.7.0"
    }
  ],
  "pip": [
    "colorama",
    "six",
    "toml",
    "pymongo",
    "gitpython",
    "psutil",
    "Xlib",
    "pyqt5"
  ],
  "archive_files": [
	{
	  "extract_path": "vendor/bin/ffmpeg_exec/windows",
	  "url": "https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.1.3-win64-static.zip",
	  "archive_type": "zip",
	  "skip_first_subfolder": true
	},
	{
	  "extract_path": "vendor/bin/ffmpeg_exec/linux",
	  "url": "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz",
	  "archive_type": "tar.xz",
	  "skip_first_subfolder": true
	}
  ]
}
